config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home', to: 'pages#home'

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord

  has_many :recipes

  validates :chefname, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  before_save { self.email = email.downcase }

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :chef

  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates :chef_id , presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
      </div>
                          
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav">
           <li><%# link_to "Chefs", chefs_path %></li>
           <li><%# link_to "All Recipes", recipes_path %></li>
           <% if false # logged_in? %>
             <li><%= link_to "ChefChat", chat_path %></li>
             <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
               <ul class="dropdown-menu">
                 <li><%# link_to "Create a new recipe", new_recipe_path %></li>
               </ul>
             </li>
           <% end %>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
             <ul class="dropdown-menu">
               <li><%# link_to "All Ingredients", ingredients_path %></li>
               <%# Ingredient.all.each do |ingredient| %>
                 <li><%# link_to ingredient.name.capitalize, ingredient_path(ingredient) %></li>
               <%# end %>
               <% if false #  logged_in? && current_chef.admin? %>
                 <li role="separator" class="divider"></li>
                 <li><%= link_to "New Ingredient", new_ingredient_path %></li>
               <% end %>
             </ul>
           </li>
         </ul>
         <form class="navbar-form navbar-left">
           <div class="form-group">
             <input type="text" class="form-control" placeholder="Search">
           </div>
           <button type="submit" class="btn btn-default">Submit</button>
          </form>

          <ul class="nav navbar-nav navbar-right">
            <% if false # logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "View your profile", chef_path(current_chef) %></li>
                  <li><%= link_to "Edit your profile", edit_chef_path(current_chef) %></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%# link_to "Log in", login_path %></li>  
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav></li></li></li></a></li></li></li></ul></span></a></li></ul></button></div></form></li></li></li></li></ul></span></a></li></li></ul></span></a></li></li></li></li></ul></div></span></span></span></span></button></div></div></nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="center">
    <h1>Welcome to MyRecipes</h1>
    <h2>The best recipe sharing app!</h2>
    <p><%= link_to "Sign up or Log in", "#", class: "btn btn-danger btn-lg btn-xlarge" %></p>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h2>Explore Recipes</h2>
    <p>We have a ton of recipes for you to explore, not sure about the app yet? Don't worry just view as a guest, we're sure you'll come back to sign-up at a later time</p>
    <p><%# link_to "View all recipes as a Guest!", recipes_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
  <div class="col-lg-4">
    <h2>Unlock all features!</h2>
    <p>Sign up for the app and unlock all it's magic, create and share recipes, hangout with chefs in the chefchat, comment on recipes you have tried out, like/dislike and much much more!</p>
    <p><%# link_to "Sign up for an account", signup_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
  <div class="col-lg-4">
    <h2>Have an ingredient, need ideas?</h2>
    <p>View our ingredients listing page and select an ingredient that you have to view recipes associated with it for cooking ideas!</p>
    <p><%# link_to "View ingredients listing", ingredients_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
</div>

app/views/recipes/index.html.erb
<h1 align="center">Listing all recipes</h1>
<hr/>

<% @recipes.each do |r| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= r.name %></h4>
      <p><%= truncate(r.description,length: 150) %></p>
      <p>
        <span class="quiet">
          <small>Created
            <%= time_ago_in_words(r.created_at) %>ago
          </small></span>
      </p>
    </div>
  </div>
<% end %>